### PR TITLE
microverse hello project pull request

### PR DESCRIPTION
**Pull request by tatouroberto**
#Hello Microverse project.

*Added the HTML file whit tag h1.
*Added the Css File to control the page styles
*Added Linter to control syntax Html and Css.

### CODE REVIEW

**Review by skyv26 — CHANGES_REQUESTED** [review]
### Hi @tatouroberto , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Clean code ✅ 

## Required Changes ♻️
- [ ] Kindly adhere to project requirements according to which you have to use [Microverse README template](https://github.com/microverseinc/readme-template) because having a good `README.md` file helps you to document your project to make it easy for any user to understand your code. 

- [ ] Please make sure that after having the copy of the `README.md` file you must have to customize that according to the needs of the project and then `re-submit` the project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AdnanOlarmmi — CHANGES_REQUESTED** [review]
Hi @tatouroberto , 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

You're Almost there, funny one eyed alien

## Highlights
- Nice work ignoring appropriate files.

## Required Changes ♻️
- [ ] As said by the previous reviewer, Kindly complete your readme section, you can follow the readme in [this repo](https://github.com/AdnanOlarmmi/Technopreneur) for inspiration.


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tatouroberto** [comment]
hello i don't if its right for me to mail you but i wish to ask section
since the project is a small one and i don't have material such as video,
live demo and deployment, is it not appropriate to omit those sections

**Review by V-Blaze — APPROVED** [review]
Hi @tatouroberto  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy

## Highlights

- Readme Looks professional 💯
-  Linters are passing👍
-  Great pull request summary🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
